version: '3.7'
services:
  app:
    build: .
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    expose:
      - "3306"
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


